### ISSUE TITLE
Add google ML thing

### ISSUE THREAD

**Issue by Soneji** [soneji/awesome-teaching#2]
https://www.instagram.com/tv/CGn-75ngGbX/?igshid=jpqqnpyf3auc

**Comment by spencer1573** [comment]
i'll take this! @Soneji

**Comment by Soneji** [comment]
👍

**Comment by spencer1573** [comment]
Hey [PR #3 ](https://github.com/Soneji/awesome-teaching/pull/3) closes this issue. thanks! @Soneji
